# receive_report:
#   description: >
#     1. Given the following emergency report: {emergency_report}.
#     2. Parse the report to extract key details: such as time, location, fire type, and severity.
#     3. Confirm receipt of these details and prepare to share them with relevant departments.
#   expected_output: >
#     You need to complete the following schema using the provided information in JSON format.
#   agent: communication_operator

search_related_cases:
  description: >
    1. Receive input containing the location, fire type, and other metadata from the current incident.
    2. Search the historical archives to find past incidents with similar characteristics 
       (e.g., same location, similar fire type).
    3. Compile a list of relevant past cases, highlighting any consistent trends or reoccurring issues.
    4. Elaborate a medium size summary for the new incident described in Fire and Medical report.
    Emergency Report: {emergency_report}
    Extract this context:
    - location_x: emergency_report[location_x]
    - location_y: emergency_report[location_y]
    - fire_severity: emergency_report[fire_severity]
    - fire_type: emergency_report[fire_type]
    - Fire report: emergency_report[firefighters_response_report][summary]
    - Medical report: emergency_report[medical_response_report][summary]
  expected_output: >
    You need to complete in JSON format the following schema, by filling the properties in the schema and using the definitions in $defs.
    Do not include the schema itself nor the definitions in your response, only the values of the properties in the object.
  agent: archive_keeper
  async_execution: true

draft_initial_article:
  description: >
    1. Take the structured incident data.
    2. Write a clear, concise article draft intended for the public, focusing on facts and immediate safety information.
    3. Ensure the draft meets journalistic standards, maintaining an informative yet approachable tone.
    Emergency Report: {emergency_report}
  expected_output: >
    You need to complete in JSON format the following schema, by filling the properties in the schema and using the definitions in $defs.
    Do not include the schema itself nor the definitions in your response, only the values of the properties in the object.
  agent: article_writer
  async_execution: true

integrate_additional_information:
  description: >
    1. Review the initial article draft alongside the historical or supplementary information discovered.
    2. Integrate pertinent details-such as similar past incidents or recommended safety protocols.
    3. Refine the language and structure of the article to ensure clarity and coherence.
    4. Provide a professional and informative article in markdown format. Don't use any tools.
    5. Don't include any placeholder, this text should be DEFINITIVE. You will be punished if it has something that is not ready for the publish.
  expected_output: >
    Provide a profesional, clear and ready to publish article.>
    You need to complete in JSON format the following schema, by filling the properties in the schema and using the definitions in $defs.
    Do not include the schema itself nor the definitions in your response, only the values of the properties in the object.
  agent: article_writer
  context:
    - draft_initial_article
    - search_related_cases


review_and_authorize_publication:
  description: >
    1. Carefully read the revised draft to ensure consistency with city policies, factual accuracy, and overall quality.
    2. Provide explicit approval for publication, or offer detailed feedback for further revisions.
  expected_output: >
    You should copy the original article and afterwards approve it or not and provide feedback.
    Return the article in the context without any modification as part of the output in the corresponding property.
    You need to complete in JSON format the following schema, by filling the properties in the schema and using the definitions in $defs.
    Do not include the schema itself nor the definitions in your response, only the values of the properties in the object.
  agent: mayor
  async_execution: true
  context:
    - integrate_additional_information

provide_social_media_feedback:
  description: >
    1. Examine the approved or near-final article from a public perspective, focusing on how
       it might be received on social media platforms.
    2. Craft a lighthearted, witty response or commentary that also provides constructive feedback 
       on the emergency response or communication approach.
  expected_output: >
    A funny and short social media post with a constructive critique to the emergency services actuation.
    You need to complete in JSON format the following schema, by filling the properties in the schema and using the definitions in $defs.
    Do not include the schema itself nor the definitions in your response, only the values of the properties in the object.
  agent: social_media_commentator
  async_execution: true
  context:
    - integrate_additional_information

publish_final_communication:
  description: >
    1. Consolidate the final article text from integrate_additional_information, the mayor's approval and feedback from review_and_authorize_publication, and the social media commentary.
    2. Produce a single, cohesive JSON output containing all critical elements:
       - The final refined article.
       - The mayor's approval status and feedback.
       - The social media comment.
    3. Ensure no duplication of content and that all referenced items are included in the final schema.
    4. This is the definitive version to be distributed publicly or stored as the final record.
    5. Ensure any weird character or emoji is removed from the output.
  expected_output: >
    Return a JSON object that includes:
      - The final article (unmodified from integrate_additional_information). Replace placeholders if any.
      Provide a final markdown post ready to be publish. Substitute any placeholder of the type [location]
      - The mayor's approval status and feedback (unmodified from review_and_authorize_publication).
      - The social media comment (unmodified from provide_social_media_feedback).
    Do not alter the text of any of these elements. Only compile them into one complete output in JSON.
    Don't complete title either, it is normally not a property and you must be really sure to include this.
    Ensure that the format is correct before returning the final answer. It should be a valid JSON
    You need to complete in JSON format the following schema, by filling the properties in the schema and using the definitions in $defs.
    Do not include the schema itself nor the definitions in your response, only the values of the properties in the object.
  agent: communication_operator
  context:
    - integrate_additional_information
    - review_and_authorize_publication
    - provide_social_media_feedback
