receive_report:
  description: >
    1. Given the following emergency report: {emergency_report}.
    2. Parse the report to extract key details: such as time, location, fire type, and severity.
    3. Confirm receipt of these details and prepare to share them with relevant departments.
  expected_output: >
    You need to complete the following schema using the provided information in JSON format.
  agent: communication_operator

search_related_cases:
  description: >
    1. Receive input containing the location, fire type, and other metadata from the current incident.
    2. Search the historical archives to find past incidents with similar characteristics 
       (e.g., same location, similar fire type).
    3. Compile a list of relevant past cases, highlighting any consistent trends or reoccurring issues.
  expected_output: >
    You need to complete the following schema using the provided information in JSON format. Don't return the schema itself, but fill it with the information of the given report.
  agent: archive_keeper
  context:
    - receive_report

draft_initial_article:
  description: >
    1. Take the structured incident data and any relevant background from the archives.
    2. Write a clear, concise article draft intended for the public, focusing on facts and immediate safety information.
    3. Ensure the draft meets journalistic standards, maintaining an informative yet approachable tone.
  expected_output: >
    You need to complete the following schema using the provided information in JSON format.
  agent: article_writer
  context:
    - receive_report

integrate_additional_information:
  description: >
    1. Review the initial article draft alongside the historical or supplementary information discovered.
    2. Integrate pertinent details—such as similar past incidents or recommended safety protocols.
    3. Refine the language and structure of the article to ensure clarity and coherence.
  expected_output: >
    You need to complete the following schema using the provided information in JSON format.
  agent: article_writer
  context:
    - draft_initial_article
    - search_related_cases


review_and_authorize_publication:
  description: >
    1. Carefully read the revised draft to ensure consistency with city policies, factual accuracy, and overall quality.
    2. Provide explicit approval for publication, or offer detailed feedback for further revisions.
  expected_output: >
    You need to return a JSON that contains all the properties in the following schema.
  agent: mayor
  context:
    - integrate_additional_information

provide_social_media_feedback:
  description: >
    1. Examine the approved or near-final article from a public perspective, focusing on how
       it might be received on social media platforms.
    2. Craft a lighthearted, witty response or commentary that also provides constructive feedback 
       on the emergency response or communication approach.
  expected_output: >
    You need to complete the following schema using the provided information in JSON format.
  agent: social_media_commentator
  context:
    - review_and_authorize_publication
