# tasks.yaml
receive_call:
  description: >
    Process the emergency call transcript and extract structured information. The transcript is, {transcript}.
  expected_output: >
    You need to complete in JSON format the following schema, by filling the properties in the schema and using the definitions in $defs.
    Do not include the schema itself nor the definitions in your response, only the values of the properties in the object.
  agent: emergency_call_agent

notify_other_crews:
  description: >
    Analyze the emergency details and determine which emergency services are required.
    Firefighters are always required for fires.
    Medical services are required if there are injuries or trapped people.
    Return the unchanged call assessment from the previous task, adding only the required services (firefighters_required and medical_services_required).
  expected_output: >
    You need to complete in JSON format the following schema, by filling the properties in the schema and using the definitions in $defs.
    Do not include the schema itself nor the definitions in your response, only the values of the properties in the object.
  agent: notification_agent
  context:
    - receive_call