receive_report:
  description: Receive the fire assessment from the Emergency Service Operator.
  expected_output: Key information such as fire location, type, severity, number of trapped individuals, and hazards.
  agent: fire_chief

allocate_firefighting_resources:
  description: Determine the necessary firefighting materials based on the fire assessment.
  expected_output: A list of required materials with their quantities.
  agent: equipment_technician

deploy_fire_combatants:
  description: Plan and execute the deployment of firefighters to the fire location.
  expected_output: Number of firefighters deployed, estimated arrival time, and prioritized firefighting activities.
  agent: firefighter

report_firefighting_response:
  description: Report a comprehensive summary of the firefighting response and actions taken.
  expected_output: A summary of firefighting activities and outcomes.
  agent: fire_chief
