%%{init: {'theme':'forest'}}%%
sequenceDiagram
    Emergency Services Dispatch->>+Emergency Services Operator: There is an emergency
    Emergency Services Operator->>Fire Fighters Captain: There is an emergency
    Fire Fighters Captain->>+Fire Fighters Engineer: There is an emergency
    Fire Fighters Engineer->>Emergency Services Dispatch: I'm on my way
