%%{init: {'theme':'forest'}}%%
mindmap
    root((Fire Emergency<br/>Response))
        Medical Services
            Medical Services Operator
            Hospital Coordinator
            Paramedic
        Forensics
            Forensics Operator
            Coroner
            Investigator
        Public Announcements
            Facilitator
            Info Agent
            Journalist
            Radio Announcer
        Emergency Services
            Dispatch
            Operator
        Fire Fighters
            Captain
            Engineer
            Firefighter
